version: "3.9"

services:
  db:
    image: postgres:15
    container_name: pp_db
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - db_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U postgres -d mydb"]
      interval: 5s
      timeout: 5s
      retries: 10

  api:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: pp_api
    environment:
      DATABASE_URL: ${DATABASE_URL}
      SECRET_KEY: ${SECRET_KEY}
      WORKERS: ${WORKERS}
      PORT: ${PORT}
      INSTALL_DEPS: "false"
      CLIENT_URL: "http://client:8100"
    depends_on:
      db:
        condition: service_healthy
    ports:
      - "8000:8000"
    restart: unless-stopped

  worker:
    build:
      context: .
      dockerfile: server/Dockerfile
    container_name: pp_worker
    environment:
      DATABASE_URL: ${DATABASE_URL}
    depends_on:
      db:
        condition: service_healthy
    command: ["bash", "-lc", "celery -A server.utils.ansible_tasks.celery_app worker --loglevel=INFO"]
    restart: unless-stopped

  client:
    build:
      context: .
      dockerfile: client/dockerfile
    container_name: pp_client
    environment:
      SERVER_HOST: api
      SERVER_PORT: ${PORT}
      SERVER_ID: 1
      METRIC_INTERVAL: 5
      DB_HOST: db
      DB_PORT: ${POSTGRES_PORT}
      DB_NAME: ${POSTGRES_DB}
      NSS_DB_USER: ${POSTGRES_USER}
      NSS_DB_PASSWORD: ${POSTGRES_PASSWORD}
    depends_on:
      - api
    ports:
      - "8100:8100"
    volumes:
      - client_data:/app/client_data
volumes:
  db_data:
  client_data:
  client_db_data:
volumes:
  db_data:
